// Các loại Action cho Inventory
export const GET_INVENTORY_REQUEST = "GET_INVENTORY_REQUEST";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
export const GET_INVENTORY_FAILURE = "GET_INVENTORY_FAILURE";

export const UPDATE_INVENTORY_REQUEST = "UPDATE_INVENTORY_REQUEST";
export const UPDATE_INVENTORY_SUCCESS = "UPDATE_INVENTORY_SUCCESS";
export const UPDATE_INVENTORY_FAILURE = "UPDATE_INVENTORY_FAILURE";

export const ADD_INVENTORY_REQUEST = "ADD_INVENTORY_REQUEST";
export const ADD_INVENTORY_SUCCESS = "ADD_INVENTORY_SUCCESS";
export const ADD_INVENTORY_FAILURE = "ADD_INVENTORY_FAILURE";

export const REDUCE_INVENTORY_REQUEST = "REDUCE_INVENTORY_REQUEST";
export const REDUCE_INVENTORY_SUCCESS = "REDUCE_INVENTORY_SUCCESS";
export const REDUCE_INVENTORY_FAILURE = "REDUCE_INVENTORY_FAILURE";

export const DELETE_INVENTORY_REQUEST = "DELETE_INVENTORY_REQUEST";
export const DELETE_INVENTORY_SUCCESS = "DELETE_INVENTORY_SUCCESS";
export const DELETE_INVENTORY_FAILURE = "DELETE_INVENTORY_FAILURE";
